language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

jobs:
  include:
    - rust: nightly
      name: "Lint with Clippy"
      install: rustup component add clippy
      script: cargo clippy --verbose --all-targets -- -D warnings

install: skip
script:
  - cargo test --verbose
