[package]
authors = ["Thomas Bahn <thomas@thomas-bahn.net>"]
description = "A SCRAM provider library."
keywords = ["scram", "authentication"]
license = "MIT"
name = "scram"
repository = "https://github.com/tomprogrammer/scram"
version = "0.0.1"

[dependencies]
data-encoding = "1.1.2"
rand = "0.3.14"
ring = "0.2.3"

[dependencies.clippy]
optional = true
version = "0.0"
