[package]
authors = ["Thomas Bahn <thomas@thomas-bahn.net>"]
description = "A SCRAM provider library."
documentation = "https://tomprogrammer.github.io/scram/scram/index.html"
keywords = ["scram", "authentication"]
license = "MIT"
name = "scram"
readme = "README.md"
repository = "https://github.com/tomprogrammer/scram"
version = "0.2.0"

[dependencies]
base64 = "0.5.2"
rand = "0.3"
ring = "0.9.4"
